spring:
  application:
    name: df-cloud-eureka-server
  profiles:
    active: dev
server:
  port: 8810
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
  instance:
    ip-address: 127.0.0.1
    prefer-ip-address: true
    hostname: localhost
    instance-id: ${eureka.instance.ip-address}:${server.port}:${spring.application.name}
